# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build

on:
  push:
    branches-ignore:  # Branches corresponding to this will not record the start of the job in GitHub Actions
      - 'mob-session'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"  # Jobs ignored in this step are marked as "skipped" in GitHub Actions

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run tests
      run: ./gradlew test
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        path: build/reports/tests/test  # Not specify name reason is workaround "zip in zip" problem, see: https://github.com/actions/upload-artifact/issues/39
      if: always()  # Keep the test result as an artifact even if tests fails

    - name: Run detekt
      run: ./gradlew detekt
    - name: Upload detekt results
      uses: actions/upload-artifact@v2
      with:
        path: build/reports/detekt  # Not specify name reason is workaround "zip in zip" problem, see: https://github.com/actions/upload-artifact/issues/39
      if: always()  # Keep the test result as an artifact even if tests fails

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.projectKey=remotemobprogramming_intellij-mob
          -Dsonar.organization=remotemobprogramming
          -Dsonar.sources=src/main
          -Dsonar.exclusions=**/*.form,**/resources
          -Dsonar.tests=src/test
          -Dsonar.junit.reportPaths=build/test-results/test
          -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
          -Dsonar.kotlin.detekt.reportPaths=build/reports//detekt/detekt.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build plugin
      run: ./gradlew buildPlugin
    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        path: build/distributions

    - name: Check plugin compatibility
      uses: ChrisCarini/intellij-platform-plugin-verifier-action@v0.0.2
      with:
        ide-versions: |
          ideaIC:2020.1
          ideaIU:2020.1
          clion:2020.1
          goland:2020.1
          pycharmPC:2020.1
          pycharmPY:2020.1
          riderRD:2020.1
          ideaIC:LATEST-EAP-SNAPSHOT
          ideaIU:LATEST-EAP-SNAPSHOT
          clion:LATEST-EAP-SNAPSHOT
          goland:LATEST-EAP-SNAPSHOT
          pycharmPC:LATEST-EAP-SNAPSHOT
          pycharmPY:LATEST-EAP-SNAPSHOT

    - uses: nowsprinting/check-version-format-action@v1
      id: version
      with:
        prefix: 'v'
    - name: Publish plugin to EAP channel
      run: ./gradlew publishPlugin
      env:
        INTELLIJ_PUBLISH_TOKEN: ${{ secrets.JETBRAINS_MARKETPLACE_TOKEN }}
        INTELLIJ_PUBLISH_CHANNEL: eap
      if: steps.version.outputs.is_valid == 'true'  # Even stable releases need to be uploaded to the eap channel. see: https://plugins.jetbrains.com/docs/marketplace/custom-release-channels.html#CustomReleaseChannels-ChannelPriorityNotice
    - name: Publish plugin to Stable channel
      run: ./gradlew publishPlugin
      env:
        INTELLIJ_PUBLISH_TOKEN: ${{ secrets.JETBRAINS_MARKETPLACE_TOKEN }}
        INTELLIJ_PUBLISH_CHANNEL: Stable
      if: steps.version.outputs.is_stable == 'true'

    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # required
      if: always() # Pick up events even if the job fails or is canceled.
