# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build

on:
  push:
    branches-ignore:  # Branches corresponding to this will not record the start of the job in GitHub Actions
      - 'mob-session'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"  # Jobs ignored in this step are marked as "skipped" in GitHub Actions

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run tests
      run: ./gradlew test
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        path: build/reports/tests/test
      if: always()  # Leave the test result as an artifact even if tests fails

    - name: Build plugin
      run: ./gradlew buildPlugin
    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        path: build/distributions

    - name: Check version format in tag
      id: version
      run: |
        if [[ ${{ github.ref }} =~ ^refs/tags/v[0-9]+(\.[0-9]+)*$ ]]; then
          echo ::set-output name=is_stable::true
        fi

    - name: Publish plugin to EAP channel
      run: ./gradlew publishPlugin
      env:
        INTELLIJ_PUBLISH_TOKEN: ${{ secrets.JETBRAINS_MARKETPLACE_TOKEN }}
        INTELLIJ_PUBLISH_CHANNEL: eap
      if: contains(github.ref, 'tags/v')  # Even stable releases need to be uploaded to the eap channel. see: https://plugins.jetbrains.com/docs/marketplace/custom-release-channels.html#CustomReleaseChannels-ChannelPriorityNotice

    - name: Publish plugin to Stable channel
      run: ./gradlew publishPlugin
      env:
        INTELLIJ_PUBLISH_TOKEN: ${{ secrets.JETBRAINS_MARKETPLACE_TOKEN }}
        INTELLIJ_PUBLISH_CHANNEL: Stable
      if: steps.version.outputs.is_stable == 'true'

    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # required
      if: always() # Pick up events even if the job fails or is canceled.
